Repository operate-first/training, pull requests merged in 2022-05, with the labels that each got.

#9 add workflows
  .github/workflows/book-open_source_basics.yml
Labels: size/M

#12 Updated the GitHub workflow to sync with an updated directory name
  .github/workflows/book-operate_first_intro.yml
Labels: approved, size/S

#13 workflow
  .github/workflows/book-open_source_licensing.yml
Labels: size/M, approved

#14 README instructions updated to latest info/workflow
  README.md
Labels: size/M, approved
